name: pull_request_workflow

on:
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  pull_request_job:
    name: Test infra on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Hashicorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-id: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-2

      - name: Iac Apply
        env:
          COMMAND_IAC: terraform
        run: cd iac
          $COMMAND_IAC init
          $COMMAND_IAC validate
          $COMMAND_IAC plan
